Shop/Controllers/GioHangController.cs
using Microsoft.AspNet.Identity; // lấy id của user.identity trong phần đăng nhập
using Shop.Models.BUS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Controllers
{
    [Authorize] //hỗ trợ bởi aspnet.identity check xem đã đăng nhập chưa
    public class GioHangController : Controller
    {

        // GET: GioHang
        public ActionResult Index()
        {
            ViewBag.TongTien = GioHangBUS.TongTien(User.Identity.GetUserId());
            return View(GioHangBUS.DanhSach(User.Identity.GetUserId()));
        }
        [HttpPost]
        public ActionResult Them(string masanpham, int soluong, int gia, string tensanpham)
        {
            try
            {
                GioHangBUS.Them(masanpham, User.Identity.GetUserId(), soluong, gia, tensanpham);
                return RedirectToAction("index");
            }
            catch
            {
                return RedirectToAction("../Shop/index");
            }

        }
        [HttpPost]
        public ActionResult CapNhat(string masanpham, int soluong, int gia, string tensanpham)
        {
            try
            {
                GioHangBUS.CapNhat(masanpham, User.Identity.GetUserId(), soluong, gia, tensanpham);
                return RedirectToAction("index");
            }
            catch
            {
                //return RedirectToAction("../Shop/index");
                return RedirectToAction("../GioHang");
            }

        }
        [HttpGet]
        public ActionResult Xoa(string masanpham)
        {
            try
            {
                GioHangBUS.Xoa(masanpham, User.Identity.GetUserId());
                return RedirectToAction("index");
            }
            catch
            {
                return RedirectToAction("../Shop/index");
            }

        }


        // update : công việc đầu tiên check <1
        //mỗi cái forecsh sẽ là 1 cái form chứ iduser , masp , so luong , sau do cap nhat lai so luong


        // xóa sản phảm đó dự vào mã sản phảm được chọn xóa , id đang thực hiện xóa
        // khi thanh toán , lưu toàn bộ xong db 

    }
}

Shop/Controllers/ThanhToanController.cs
using Microsoft.AspNet.Identity;
using Shop.Models.BUS;
using ShopDegreyConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Controllers
{
    public class ThanhToanController : Controller
    {
        [Authorize]
        // GET: ThanhToan
        public ActionResult Index()
        {
            List<GioHang> ds = GioHangBUS.DanhSach(User.Identity.GetUserId()).ToList();
            if (ds.Count() == 0)
            {
                return RedirectToAction("../Shop/index");
            }
            ViewBag.TongTien = GioHangBUS.TongTien(User.Identity.GetUserId());
            return View(ds);
        }
        [HttpPost]
        public ActionResult Them(string nguoinhan, string sdt, string diachi)
        {
            //try
            //{
                ThanhToanBUS.ThemOrder(nguoinhan, sdt, diachi, User.Identity.GetUserId());
                return RedirectToAction("../Shop/Index");
            //}
            //catch
            //{
            //    return RedirectToAction("../GioHang/Index");
            //}

        }
    }
}

Shop/Views/GioHang/Index.cshtml
@model IEnumerable<ShopDegreyConnection.GioHang>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

 
    <!-- Cart -->
    <section class="cart bgwhite p-t-70 p-b-100">
        <div class="container">
            <!-- Cart item -->
            <div class="container-table-cart pos-relative">
                <div class="wrap-table-shopping-cart bgwhite">
                    <table class="table-shopping-cart">

                        <tr class="table-head">
                            <th class="column-1">Sản Phẩm</th>
                            <th></th>
                            <th class="column-2 text-center">Tên Sản Phẩm</th>
                            <th class="column-3 text-center">Giá Tiền</th>
                            <th class="column-4 p-l-70">Số Lượng</th>
                            <th class="column-5 text-center">Tổng Tiền @Model.Count()</th>
                        </tr>
                        @foreach (var item in Model) 
                        {
                           
                    <tr class="table-row">

                        <td class="column-1">
                            <div class="cart-img-product b-rad-4 o-f-hidden p-r-50">
                                <img src="~/Asset/images/@item.Hinh" alt="IMG-PRODUCT">
                            </div>
                        </td>
                        @using (Html.BeginForm("CapNhat", "GioHang", FormMethod.Post))
                        {

                            <td >
                                <div>
                                    <input type="hidden" name="masanpham" value="@item.MaSanPham" />
                                    <input type="hidden" name="tensanpham" value="@item.TenSanPham" />
                                    <input type="hidden" name="gia" value="@item.Gia" />
                                </div>
                            </td>
                            @Html.Partial("_GioHang", Shop.Models.BUS.ShopBUS.ChiTiet(item.MaSanPham.ToString()))

                            <td class="column-4 text-center">
                                <input class="size8 m-text18 t-center num-product " type="number" value="@item.SoLuong" min="1" max="1000" name="soluong" />  <input type="submit"  value="Cập Nhật" /> <br />

                            </td>

                            <td class="column-5 text-center"><span>@item.TongTien VNĐ</span></td>
                        }
                        <td>
                            <a href="@Url.Action("Xoa","GioHang",new { masanpham= item.MaSanPham})" class="btn btn-default pull-right">Xóa</a>
                        </td>
                    </tr>

                        }
                    </table>
                </div>

            

                <!-- Total -->
                <div class="bo9 w-size18 p-l-40 p-r-40 p-t-30 p-b-38 m-t-30 m-r-0 m-l-auto p-lr-15-sm">
                    <h5 class="m-text20 p-b-24">
                        ĐƠN HÀNG
                    </h5>

                    <!--  -->
                    @*<div class="flex-w flex-sb-m p-b-12">
                        <span class="s-text18 w-size19 w-full-sm">
                            Subtotal:
                        </span>

                        <span class="m-text21 w-size20 w-full-sm">
                            $39.00
                        </span>
                    </div>*@

                    <!--  -->
                    <div class="flex-w flex-sb bo10 p-t-15 p-b-20">
                        <span class="s-text18 w-size19 w-full-sm">
                           GIAO HÀNG:
                        </span>

                        <div class="w-size20 w-full-sm">
                            <p class="s-text8 p-b-23">
                                (*) Free shipping từ hóa đơn 500.000 VNĐ tại TP.HCM và 1.000.000 VNĐ tại các tỉnh khác.
                            </p>

                          

                          
                            @*<div class="size13 bo4 m-b-22">
                                <input class="sizefull s-text7 p-l-15 p-r-15" type="text" name="postcode" placeholder="Postcode / Zip">
                            </div>*@

                            @*<div class="size14 trans-0-4 m-b-10">
                                
                                <button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
                                    Update Totals
                                </button>
                            </div>*@
                        </div>
                    </div>

                    <!--  -->
                    <div class="flex-w flex-sb-m p-t-26 p-b-30">
                        <span class="m-text22 w-size19 w-full-sm">
                           TỔNG TIỀN:
                        </span>

                        <span class="m-text21 w-size20 w-full-sm">
                            @ViewBag.TongTien VNĐ
                        </span>
                    </div>

                    <div class="size15 trans-0-4">
                        <!-- Button -->
                       
                            <a href="@Url.Action("index","ThanhToan")" class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">THANH TOÁN</a>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>



 
    <!-- Back to top -->
    <div class="btn-back-to-top bg0-hov" id="myBtn">
        <span class="symbol-btn-back-to-top">
            <i class="fa fa-angle-double-up" aria-hidden="true"></i>
        </span>
    </div>

    <!-- Container Selection -->
    <div id="dropDownSelect1"></div>
    <div id="dropDownSelect2"></div>



    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Asset/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Asset/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Asset/vendor/bootstrap/js/popper.js"></script>
    <script type="text/javascript" src="~/Asset/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Asset/vendor/select2/select2.min.js"></script>
    <script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});

		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect2')
		});
    </script>
    <!--===============================================================================================-->
    <script src="~/Asset/js/main.js"></script>