Shop/Areas/Admin/Controllers/LoaiSanPhamAdminController.cs
using Shop.Models.BUS;
using ShopDegreyConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Areas.Admin.Controllers
{
    public class LoaiSanPhamAdminController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: Admin/LoaiSanPhamAdmin
        public ActionResult Index()
        {
            var db = LoaiSanPhamBUS.DanhSachAdmin();
            return View(db);
        }

        // GET: Admin/LoaiSanPhamAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/LoaiSanPhamAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiSanPhamAdmin/Create
        [HttpPost]
        public ActionResult Create(LoaiSanPham lsp) // return view ở create sau đó request ở httppost
        {
            try
            {
                LoaiSanPhamBUS.InsertLSP(lsp); // gọi hàm InsertLSP của LoaiSanPhamBUS vào
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSanPhamAdmin/Edit/5
        public ActionResult Edit(String id)    // biến truyền vào là id 
        {
            //load db theo id
            var db = LoaiSanPhamBUS.ChiTietAdmin(id);
            return View(db);
        }

        // POST: Admin/LoaiSanPhamAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(String id, LoaiSanPham lsp)
        {
            try
            {
                // TODO: Add update logic here
                LoaiSanPhamBUS.EditLSP(id, lsp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // GET: Admin/LoaiSanPhamAdmin/Delete/5
        public ActionResult XoaTamThoi(String id, LoaiSanPham lsp)
        {
            try
            {            
                LoaiSanPhamBUS.DeleteLSP(id, lsp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Admin/LoaiSanPhamAdmin/Delete/5
        //[HttpPost]
        //public ActionResult XoaTamThoi(String id, LoaiSanPham lsp)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here
        //        lsp.TinhTrang = "1";
        //        LoaiSanPhamBUS.EditLSP(id, lsp);
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
        // GET: Admin/LoaiSanPhamAdmin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/LoaiSanPhamAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Shop/Areas/Admin/Views/LoaiSanPhamAdmin/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<h2>Create</h2>

<style>
    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }
</style>



<div style="margin:auto;">
    @using (Html.BeginForm("Create", "LoaiSanPhamAdmin", FormMethod.Post, new { @style = "width:50%; margin:auto;" }))
    {
        <label for="fname">Mã Loại Sản Phẩm</label>
        <input type="text" id="fname" name="MaLoaiSanPham" style="background-color:#5d5e63;" placeholder="Mã Loại Sản Phẩm.." required>

        <label for="lname">Tên Loại Sản Phẩm</label>
        <input type="text" id="lname" name="TenLoaiSanPham" style="background-color:#5d5e63;" placeholder="Tên Loại Sản Phẩm.." required>

        <label for="country">Tình Trạng</label>
        <select id="country" style="width:30%;background-color:#5d5e63;" name="TinhTrang" required>
            <option value="0" selected>Chưa Khóa</option>
            <option value="1">Đã Khóa</option>
        </select>
        <input type="submit" value="Xác nhận Thêm loại sản phẩm" />
    }
</div>

Shop/Areas/Admin/Views/LoaiSanPhamAdmin/Edit.cshtml
@model  ShopDegreyConnection.LoaiSanPham
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}


<style>
    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }
</style>



<div style="margin:auto;">

    @using (Html.BeginForm("Edit", "LoaiSanPhamAdmin", FormMethod.Post, new { @style = "width:50%; margin:auto;" }))

    {
        <label for="fname">Mã Loại Sản Phẩm</label>
        <input type="text" id="fname" name="MaLoaiSanPham" style="background-color:#5d5e63;" placeholder="Mã Loại Sản Phẩm.." required value="@Model.MaLoaiSanPham" readonly>

        <label for="lname">Tên Loại Sản Phẩm</label>
        <input type="text" id="lname" name="TenLoaiSanPham" style="background-color:#5d5e63;" placeholder="Tên Loại Sản Phẩm.." required value="@Model.TenLoaiSanPham">

        <label for="country">Tình Trạng</label>
        <select id="country" style="width:30%;background-color:#5d5e63;" name="TinhTrang" required>
            @if (Model.TinhTrang == "1")
            {
                <option value="0">Chưa Khóa</option>
                <option value="1" selected>Đã Khóa</option>
            }
            else
            {
                <option value="0" selected>Chưa Khóa</option>
                <option value="1">Đã Khóa</option>
            }
        </select>
        <input type="submit" value="Xác nhận Chỉnh Sửa" />
    }
</div>

Shop/Areas/Admin/Views/LoaiSanPhamAdmin/Index.cshtml
@model  IEnumerable<ShopDegreyConnection.LoaiSanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<h2>Quản Lý Loại Sản Phẩm</h2>

<style>
    table {
        border-collapse: collapse;
        width: 50%;
        margin: auto;
    }

    th, td {
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #5d5e63;
    }

    th {
        background-color: #2a9fd6;
        color: white;
    }
</style>
<table>
    <tr>
        <th>Mã Loại Sản Phẩm</th>
        <th>Tên Loại Sản Phẩm</th>
        <th>Tình Trạng</th>
        <th colspan="2">
            <a href="@Url.Action("Create","LoaiSanPhamAdmin")"><img style="max-width:40px;max-height:40px" src="~/Asset/images/add.png" /></a>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MaLoaiSanPham</td>
            <td>@item.TenLoaiSanPham</td>
            <td>@item.TinhTrang</td>
            <td><a href="@Url.Action("Edit","LoaiSanPhamAdmin",new { id = @item.MaLoaiSanPham })"><img style="max-width:40px;max-height:40px" src="~/Asset/images/icons/edit.png" /></a></td>
            <td><a href="@Url.Action("XoaTamThoi","LoaiSanPhamAdmin",new { id = @item.MaLoaiSanPham })"><img style="max-width:40px;max-height:40px" src="~/Asset/images/icons/delete.png" /></a></td>
        </tr>
    }

</table>