Shop/Areas/Admin/Controllers/SanPhamAdminController.cs
using PagedList;
using ShopDegreyConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Xml.Linq;
using System.IO;
using Shop.Models.BUS;

namespace Shop.Areas.Admin.Controllers
{
    public class SanPhamAdminController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: Admin/SanPhamAdmin
        public ActionResult Index(int page = 1, int pagesize = 12)
        {

            return View(ShopBUS.DanhSachSP().ToPagedList(page, pagesize));
        }

        // GET: Admin/SanPhamAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        public string LoadImages(string id)
        {
            var product = ShopBUS.ChiTiet(id);
            var images = product.Hinh;
            return images;
        }
        public string SaveImagePhoto(string productName)
        {
            var basePath = "~/Asset/images";
            var filename = "";
            var path = Server.MapPath(basePath);
            var savedFileName = "";

            HttpPostedFileBase file = Request.Files[0];
            if (file.ContentLength > 0)
            {
                filename = productName + Path.GetExtension(file.FileName);
                savedFileName = Path.Combine(path, filename);
                file.SaveAs(savedFileName);
            }
            //filename = (basePath + "/" + fileName).ToAbsoluteUrl()
            return string.Format("{0}", filename);
        }
        // GET: Admin/SanPhamAdmin/Create
        public ActionResult Create()
        {

            ViewBag.MaLoaiSanPham = new SelectList(LoaiSanPhamBUS.DanhSach(), "MaLoaiSanPham", "TenLoaiSanPham");
            return View();
        }

        // POST: Admin/SanPhamAdmin/Create
        [HttpPost]
        //[ValidateInput(false)]
        public ActionResult Create(SanPham sp)
        {
            try
            {
                sp.TinhTrang = "0";
                sp.SoLuongDaBan = 0;
                sp.LuotXem = 0;
                sp.TinhTrang = "1";
                sp.Hinh = SaveImagePhoto(sp.MaSanPham);
                // TODO: Add insert logic here
                ShopBUS.InsertSP(sp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/SanPhamAdmin/Edit/5
        public ActionResult Edit(String id)
        {

            ViewBag.MaLoaiSanPham = new SelectList(LoaiSanPhamBUS.DanhSach(), "MaLoaiSanPham", "TenLoaiSanPham", ShopBUS.ChiTiet(id).MaLoaiSanPham);
            return View(ShopBUS.ChiTiet(id));
        }

        // POST: Admin/SanPhamAdmin/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(String id, SanPham sp)
        {
            var tam = ShopBUS.ChiTiet(id);
            try
            {
                // TODO: Add update logic here
                sp.Hinh = tam.Hinh;
                if (sp.SoLuongDaBan > 10000)
                {
                    sp.SoLuongDaBan = 0;
                }
                else { sp.SoLuongDaBan = tam.SoLuongDaBan; }
                if (sp.LuotXem > 10000) { sp.LuotXem = 0; } else { sp.LuotXem = tam.LuotXem; }
                sp.TinhTrang = tam.TinhTrang;
                ShopBUS.UpdateSP(id, sp);
                // TODO: Add insert logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       
        public ActionResult Delete(String id, SanPham sp)
        {
           // var tam = ShopBUS.ChiTiet(id);
            try
            {
                // TODO: Add delete logic here
                //if (tam.SoLuongDaBan > 10)
                //{
                //    tam.SoLuongDaBan = 0;
                //}
                //if (tam.LuotXem > 10) { tam.LuotXem = 0; }
                //if (tam.TinhTrang == "1         ") { tam.TinhTrang = "0         "; }
                //else
                //{
                //    tam.TinhTrang = "1         ";
                //}

                //ShopBUS.UpdateSP(id, tam);
                ShopBUS.DeleteSP(id, sp);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Shop/Areas/Admin/Views/SanPhamAdmin/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}


<style>
    input [type-text] {
        width: 100%;
        height: 40px;
        background: black;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ff0000;
        border-radius: 2px;
        box-sizing: border-box;
        color: black !important;
    }

    input [type-number] {
        width: 100%;
        height: 40px;
        background: black;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ff0000;
        border-radius: 4px;
        box-sizing: border-box;
        color: black !important;
    }

    input [type-submit] {
        width: 100%;
        background-color: #2a9fd6;
        color: black;
        
        padding: 14px 20px;
        margin: 8px 0;
        display: inline-block;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input [type-submit]:hover {
            background-color: #45a049;
        }
</style>

@using (Html.BeginForm("Create", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table style="width:80%; margin:auto; background:black;">
        <tr>
            <td> Mã Sản Phẩm</td>
            <td> <input style="width:300px; background-color:black; float:left; height:35px" maxlength="11" type="text" name="MaSanPham" required /></td>
            <td rowspan="8">
                <div style="width:320px;height:300px">
                    &nbsp;
                </div>
            </td>
        </tr>

        <tr>
            <td> Mã Loại Sản Phẩm</td>
            <td>
                @Html.DropDownList("MaLoaiSanPham", null, new { @style = "float:left;width:300px; background:black; height:30px;" })
            </td>
        </tr>

        <tr>
            <td> Tên Sản Phẩm</td>
            <td>
                <input style="width:300px;background-color:black; float:left; height:35px" maxlength="50" type="text" name="TenSanPham" required />
            </td>
        </tr>

        <tr>
            <td> Hình </td>
            <td> <input type="file" name="Hinh" required /></td>
        </tr>

        <tr>
            <td> Giá </td>
            <td> <input style="width:300px;float:left;background-color:black; " type="number" name="Gia" required /></td>
        </tr>

        <tr>
            <td style="width:300px;"> Ghi Chú </td>
            <td colspan="2"><textarea class="ckeditor" name="GhiChu" style="width:300px;height:150px;margin-top:100px;   max-width:100px;max-height:600px;" rows="4" cols="30"></textarea></td>
        </tr>

      

        <tr>
            <td colspan="3">
                <input style="height:40px;width:300px;margin-left:32%; margin-top:30px; background:#016ABC; color:#fff; border: 1px solid #eee;  border-radius:20px;
    " type="submit" name="btn btn-default pull-right" value="Hoàn Tất Thêm Sản Phẩm" />
            </td>
        </tr>
    </table>
}

Shop/Areas/Admin/Views/SanPhamAdmin/Edit.cshtml
@model  ShopDegreyConnection.SanPham
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}


<style>
    input [type-text] {
        width: 100%;
        height: 40px;
        background: black;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ff0000;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input [type-number] {
        width: 100%;
        height: 40px;
        background: black;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ff0000;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input [type-submit] {
        width: 100%;
        height: 40px;
        background-color: #2a9fd6;
        color: black;
        padding: 14px 50px;
        padding-top:100px;
        margin: 8px 0;
        display: inline-block;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input [type-submit]:hover {
            background-color: #45a049;
        }
</style>
<script src="~/Areas/AssetAdmin/js/product/previewFile.js"></script>
 @using (Html.BeginForm("Edit", "SanPhamAdmin", FormMethod.Post,new { enctype = "multipart/form-data" }))
 { 
    <table style="width:80%; margin:auto; background:black;">
        <tr>
            <td> Mã Sản Phẩm</td>
            <td> <input style="width:300px; float:left; height:35px ;background-color:black;" maxlength="11" type="text" name="MaSanPham" required readonly value="@Model.MaSanPham" /></td>
            <td rowspan="8">
                <div>
                    <img id="target" class="img" src="~/Asset/images/@Model.Hinh"  style="float:right;width:320px;height:300px" />
                </div>
            </td>
        </tr>

        <tr>
            <td> Mã Loại Sản Phẩm</td>
            <td>
                @Html.DropDownList("MaLoaiSanPham", null, new { @style = "float:left;width:300px; background:black; height:30px;" })
            </td>
        </tr>

        <tr>
            <td> Tên Sản Phẩm</td>
            <td>
                <input style="width:300px; float:left; height:35px; background-color:black;" maxlength="50 " type="text" name="TenSanPham" value="@Model.TenSanPham" required />
            </td>
        </tr>

        <tr>
            <td> Hình </td>
            <td> <input type="file" name="Hinh"  /></td>
        </tr>

        <tr>
            <td> Giá </td>
            <td> <input style="width:300px;float:left;background-color:black;" type="number" name="Gia" required value="@Model.Gia" /></td>
        </tr>

        <tr>
            <td> Ghi Chú </td>
            <td> <input style="width:300px;float:left;background-color:black;" type="text" name="Ghi Chu" required value="@Model.GhiChu" /></td>
        </tr>

       

        <tr>
            <td colspan="3">
                <input style="height:40px;width:300px;margin-left:32%; background:#016ABC; color:#fff; border: 1px solid #eee;  border-radius:20px;
    box-shadow:5px 5px 5px #eee;" type="submit" name="btn btn-default pull-right" value="Xác nhận Chỉnh Sửa" />
            </td>
        </tr>
    </table>
}

Shop/Areas/Admin/Views/SanPhamAdmin/Index.cshtml
@model PagedList.IPagedList<ShopDegreyConnection.SanPham>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}


<style>
    table {
        border-collapse: collapse;
        width: 80%;
        margin: auto;
    }

    th, td {
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #5d5e63;
    }

    th {
        background-color: #2a9fd6;
        color: white;
    }
</style>
<h2>Quản Lý Sản Phẩm</h2>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
<table>
    <tr>
        <th>Mã Sản Phẩm</th>
        <th>Tên Sản Phẩm</th>
        <th>Hình Ảnh</th>
        <th>Tình Trạng</th>
        <th colspan="2">
            <a href="@Url.Action("Create","SanPhamAdmin")"><img style="max-width:40px;max-height:40px" src="~/Asset/images/icons/add.png" /></a>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        string imgMainPath = "";
        if (!string.IsNullOrEmpty(@item.Hinh))
        {
            imgMainPath = "/Asset/images/" + @item.Hinh.Split(';')[0];
        }
    <tr>
        <td>@item.MaSanPham</td>
        <td>@item.TenSanPham</td>


        <td><img src="@imgMainPath" style="width:55px;height:55px;" /></td>
        <td>@item.TinhTrang</td>
        <td><a href="@Url.Action("Edit","SanPhamAdmin",new { id = @item.MaSanPham })"><img style="max-width:40px;max-height:40px" src="~/Asset/images/icons/edit.png" /></a></td>
        <td><a href="@Url.Action("Delete","SanPhamAdmin",new { id = @item.MaSanPham })"><img style="max-width:40px;max-height:40px" src="~/Asset/images/icons/delete.png" /></a></td>
    </tr>
    }

</table>
<!-- Modal -->
<div class="modal fade" id="imagesManange" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Quản Lý Ảnh</h4>
            </div>
            <div class="modal-body">
                <div id="imageList">
                </div>
                <div class="clear"></div>
                <input type="button" id="btnChooImages" class="btn btn-primary" value="Chọn ảnh" />
                <input type="hidden" id="hidProductID" value="0" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btnSaveImages">Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>